### ISSUE TITLE
I don't know how to make the dataframe and landmarks.npy

### ISSUE THREAD

**Issue by Gepeng18** [KBacsa/kiran_nii#1]
Hi! KBacsa .Could you provide me with the .py source code  for making _dataframe_ and __landmarks.npy_? Thank you very much!

**Comment by Gepeng18** [comment]
@KBacsa  Hi! KBacsa. Sorry to bother you!  Hope you can help me! Thank you very much

**Comment by KBacsa** [comment]
I don't have the codes on me right now, but it's fairly simple to generate the data. For each frame, use the dlab detector in python, then save the landmarks into a numpy array. Save the array as frame_name + '_landmarks.npy'. The dataframe is simply generated by loading the CSV files given with the AffectNet dataset using pandas.
